/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Enum {
  stringEnum: StringEnum;
  impliedStringEnum: "a" | "b" | "c";
  booleanEnum: true;
  impliedBooleanEnum: true;
  integerEnum: -1 | 0 | 1;
  impliedIntegerEnum: -1 | 0 | 1;
}

export const enum StringEnum {
  a = "a",
  b = "b",
  c = "c"
}
