/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Intersection = A &
  B & {
    c: string;
    d: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };

export interface A {
  a?: string;
  [k: string]: unknown;
}
export interface B {
  b?: string;
  [k: string]: unknown;
}
