/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A string with title and enum defined does produce a duplicate Interface
 */
export type FifthDefinitionString = "one" | "two" | "three";
export type Six = number;

export interface LocallyReferencedManifest {
  /**
   * Behaviour is the same if definition is referenced as prop within a container
   */
  firstContainer?: {
    first?: FirstDefinition;
    [k: string]: unknown;
  };
  second?: UnrelatedTitle;
  third?: ThirdDefinition;
  fourth?: FourthDefinitionSimpleObject;
  fifth?: FifthDefinitionString;
  sixth?: Six;
  [k: string]: unknown;
}
/**
 * Title matches definition key for kicks
 */
export interface FirstDefinition {
  name?: string;
  [k: string]: unknown;
}
/**
 * Title is unrelated to definition key and behaviour is the same
 */
export interface UnrelatedTitle {
  name?: string;
  [k: string]: unknown;
}
/**
 * Definition has no title and produces no duplicate Interface
 */
export interface ThirdDefinition {
  name?: string;
  [k: string]: unknown;
}
/**
 * A simple object type with title set and no properties defined produces no duplicate Interface
 */
export interface FourthDefinitionSimpleObject {
  [k: string]: unknown;
}
