/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Union = A | B;
export type A = C | D;
export type B = C | D;

export interface C {
  c?: string;
}
export interface D {
  d?: string;
}
