/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AdditionalPropertiesDefaultToTrue {
  a?: {
    [k: string]: unknown;
  };
  b?: {};
  c?: {
    [k: string]: unknown;
  };
  d?: {
    [k: string]: number;
  };
  e?: E;
  [k: string]: unknown;
}
export interface E {
  [k: string]: unknown;
}
