/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ArrayOfEnum {
  namedEnum: NamedEnum[];
  tuples?: [] | [string] | [string, NamedEnum2];
}

export const enum NamedEnum {
  One = 1,
  Two = 2,
  Three = 3
}
export const enum NamedEnum2 {
  One = 1,
  Two = 2,
  Three = 3
}
