/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Countries = {
  id: string;
  name: string;
}[];

export interface ArrayOfSchema {
  countries?: Countries;
  tuple?:
    | []
    | [
        {
          foo?: string;
        }
      ]
    | [
        {
          foo?: string;
        },
        {
          bar?: number;
        }
      ];
}
