/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Deep {
  foo:
    | (
        | number
        | Foo
        | Bar
        | {
            baz?: number;
          }
      )
    | Bar;
}
export interface Foo {
  a: string;
  b: number;
}
export interface Bar {
  a: string;
}
