/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @deprecated
 * comment
 */
export interface ExampleSchema {
  /**
   * @deprecated
   */
  firstName: string
  /**
   * @deprecated
   * Hi, my name's Doechii, this will be in a  comment
   */
  middleName?: string
  /**
   * nested comment
   */
  lastName?: string
  description?: string
}
