/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EnumFromDefinition = 'a' | 'b' | 'c'

export interface Enum {
  stringEnum: 'a' | 'b' | 'c'
  impliedStringEnum: 'a' | 'b' | 'c'
  booleanEnum: true
  impliedBooleanEnum: true
  integerEnum: -1 | 0 | 1
  impliedIntegerEnum: -1 | 0 | 1
  numberEnum?: -1.1 | 0 | 1.2
  namedIntegerEnum?: NamedIntegerEnum
  impliedNamedIntegerEnum: ImpliedNamedIntegerEnum
  impliedHeterogeneousEnum?: -20.1 | null | 'foo' | false
  namedIntegerEnumTitle: NamedInteger
  impliedNamedIntegerEnumTitle: ImpliedNamedInteger
  enumThatComesFromADefinition?: EnumFromDefinition
  propertyWithAnEnum?: {
    enumThatComesFromADefinition?: EnumFromDefinition
    [k: string]: unknown
  }
}

export const enum NamedIntegerEnum {
  One = 1,
  Two = 2,
  Three = 3
}
export const enum ImpliedNamedIntegerEnum {
  Four = 4,
  Five = 5,
  Six = 6
}
export const enum NamedInteger {
  One = 1,
  Two = 2,
  Three = 3
}
export const enum ImpliedNamedInteger {
  Four = 4,
  Five = 5,
  Six = 6
}
