/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Extends extends Base1, Base2 {
  foo: string
}
export interface Base1 {
  firstName: string
  lastName: string
}
export interface Base2 {
  age: number
}
