/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Intersection = Car | Truck
export type Car = Vehicle & {
  numDoors: number
  [k: string]: unknown
}
export type Vehicle = Thing & {
  year: number
  [k: string]: unknown
}
export type Truck = Vehicle & {
  numAxles: number
  [k: string]: unknown
}

export interface Thing {
  name: string
  [k: string]: unknown
}
