/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Intersection = {
  a: A
  b: B
} & (C | D)

export interface A {
  a: string
}
export interface B {
  b: string
}
export interface C {
  c: string
}
export interface D {
  d: string
}
