/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Intersection = A | B;
export type A = Base & {
  b?: B;
};
export type B = Base & {
  x?: string;
};

export interface Base {
  y?: string;
}
