/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Array of authorized user ids.
 */
export type UserIdArray = string[];

/**
 * My cool schema
 */
export interface ExampleSchema {
  users?: UserIdArray;
}
