/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type C = number;
export type D = number;

export interface Test {
  a?: A;
  b?: A | B;
  c?: C | D;
  d?: C | D;
  e?: D;
  f?: A | B | C | D;
}
export interface A {
  name?: string;
}
export interface B {
  name?: string;
}
