/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LastName = string;

export interface UnreachableDefinition {
  b?: {
    likesDogs?: boolean;
  };
}
/**
 * This interface was referenced by `UnreachableDefinition`'s JSON-Schema
 * via the `definition` "a".
 */
export interface A {
  firstName?: string;
  lastName?: LastName;
}
