/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StrictIndexSignatures {
  maybe?: string;
  complex?: {
    maybe?: string;
    [k: string]: Leaf | undefined;
  };
  [k: string]: string | undefined;
}
export interface Leaf {
  maybe?: string;
  [k: string]: unknown;
}
