/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type A = string;

export interface OptimizableSchema2 {
  a: A;
  b: B;
  c: B | C;
  d: {};
  e: {};
}
export interface B {}
export interface C {}
