/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type A = string

export interface OptimizableSchema2 {
  a: A
  b: B
  c: B | C
  d: {
    [k: string]: unknown
  }
  e: {
    [k: string]: unknown
  }
}
export interface B {
  [k: string]: unknown
}
export interface C {
  [k: string]: unknown
}
