/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Parent`'s JSON-Schema definition
 * via the `patternProperty` "^[0-9]+".
 */
export type NumberChild = number
/**
 * This interface was referenced by `Parent`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z]+".
 */
export type StringChild = string

export interface Parent {
  [k: string]: unknown
}
