/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CoreSchemaMetaSchema = {
  $id?: string;
  $schema?: string;
  $ref?: string;
  $comment?: string;
  title?: string;
  description?: string;
  default?: unknown;
  readOnly?: boolean;
  writeOnly?: boolean;
  examples?: unknown[];
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: number;
  minimum?: number;
  exclusiveMinimum?: number;
  maxLength?: NonNegativeInteger;
  minLength?: NonNegativeIntegerDefault0;
  pattern?: string;
  additionalItems?: CoreSchemaMetaSchema;
  items?: CoreSchemaMetaSchema | SchemaArray;
  maxItems?: NonNegativeInteger;
  minItems?: NonNegativeIntegerDefault0;
  uniqueItems?: boolean;
  contains?: CoreSchemaMetaSchema;
  maxProperties?: NonNegativeInteger;
  minProperties?: NonNegativeIntegerDefault0;
  required?: StringArray;
  additionalProperties?: CoreSchemaMetaSchema;
  definitions?: {
    [k: string]: CoreSchemaMetaSchema;
  };
  properties?: {
    [k: string]: CoreSchemaMetaSchema;
  };
  patternProperties?: {
    [k: string]: CoreSchemaMetaSchema;
  };
  dependencies?: {
    [k: string]: CoreSchemaMetaSchema | StringArray;
  };
  propertyNames?: CoreSchemaMetaSchema;
  const?: unknown;
  /**
   * @minItems 1
   */
  enum?: [unknown, ...unknown[]];
  type?: SimpleTypes | [SimpleTypes, ...SimpleTypes[]];
  format?: string;
  contentMediaType?: string;
  contentEncoding?: string;
  if?: CoreSchemaMetaSchema;
  then?: CoreSchemaMetaSchema;
  else?: CoreSchemaMetaSchema;
  allOf?: SchemaArray;
  anyOf?: SchemaArray;
  oneOf?: SchemaArray;
  not?: CoreSchemaMetaSchema;
} & CoreSchemaMetaSchema &
  boolean;
export type NonNegativeInteger = number;
export type NonNegativeIntegerDefault0 = NonNegativeInteger;
/**
 * @minItems 1
 */
export type SchemaArray = [CoreSchemaMetaSchema, ...CoreSchemaMetaSchema[]];
export type StringArray = string[];
export type SimpleTypes = "array" | "boolean" | "integer" | "null" | "number" | "object" | "string";
