/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RealWorld {}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "mainMenu".
 */
export interface MainMenu {
  items?: {
    type?: "link" | "subMenu";
    label: string;
    subMenu?: {
      column1?: (
        | {
            appearance?: "primary" | "secondary" | "arrow";
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuLink";
          }
        | {
            content: string;
            id?: string;
            blockName?: string;
            blockType: "menuDescription";
          }
        | {
            media: string | Media;
            headline: string;
            link?: {
              type?: "reference" | "custom";
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuFeature";
          }
      )[];
      enableColumn2?: boolean;
      column2?: (
        | {
            appearance?: "primary" | "secondary" | "arrow";
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuLink";
          }
        | {
            content: string;
            id?: string;
            blockName?: string;
            blockType: "menuDescription";
          }
        | {
            media: string | Media;
            headline: string;
            link?: {
              type?: "reference" | "custom";
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuFeature";
          }
      )[];
    };
    link?: {
      type?: "reference" | "custom";
      reference:
        | {
            value: string | Page;
            relationTo: "pages";
          }
        | {
            value: string | Post;
            relationTo: "posts";
          }
        | {
            value: string | Housing;
            relationTo: "housing";
          };
      url: string;
    };
    id?: string;
  }[];
  secondaryItems?: {
    link?: {
      type?: "reference" | "custom";
      label: string;
      reference:
        | {
            value: string | Page;
            relationTo: "pages";
          }
        | {
            value: string | Post;
            relationTo: "posts";
          }
        | {
            value: string | Housing;
            relationTo: "housing";
          };
      url: string;
    };
    id?: string;
  }[];
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  breadcrumbs?: {
    doc?: string | Page;
    url?: string;
    label?: string;
    id?: string;
  }[];
  title: string;
  showBreadcrumbs?: boolean;
  hero?: {
    type:
      | "basic"
      | "content"
      | "contentMedia"
      | "contentMedia2"
      | "contentSidebar"
      | "columnsBelow"
      | "quickNav"
      | "fullscreenBackground"
      | "fullscreenSlider";
    basic?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    content?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    contentMedia?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      media: string | Media;
    };
    contentMedia2?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      media: string | Media;
    };
    contentSidebar?: {
      mainContent?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      sidebarContent?: {}[];
    };
    columnsBelow?: {
      backgroundMedia: string | Media;
      useOverlay?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      columns?: {
        heading: string;
        description: string;
        link?: {
          type?: "reference" | "custom";
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    fullscreenBackground?: {
      invertColors?: boolean;
      backgroundMedia: string | Media;
      useOverlay?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    quickNav?: {
      invertColors?: boolean;
      backgroundMedia: string | Media;
      useOverlay?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      columns?: {
        heading: string;
        description: string;
        link?: {
          type?: "reference" | "custom";
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    fullscreenSlider?: {
      useStaticContent?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      slides?: {
        backgroundMedia: string | Media;
        useOverlay?: boolean;
        richText?: {}[];
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
      }[];
    };
  };
  layout?: (
    | {
        appearance?: "default" | "condensed";
        sections?: {
          label: string;
          openOnInit?: boolean;
          columns?: {
            width: "oneThird" | "half" | "twoThirds" | "full";
            alignment: "left" | "center" | "right";
            richText?: {}[];
            links?: {
              link?: {
                type?: "reference" | "custom";
                label: string;
                reference:
                  | {
                      value: string | Page;
                      relationTo: "pages";
                    }
                  | {
                      value: string | Post;
                      relationTo: "posts";
                    }
                  | {
                      value: string | Housing;
                      relationTo: "housing";
                    };
                url: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "accordion";
      }
    | {
        introContent?: {}[];
        id?: string;
        blockName?: string;
        blockType: "blackbaudForm";
      }
    | {
        invertColors?: boolean;
        backgroundMedia?: string | Media;
        useOverlay?: boolean;
        richText?: {}[];
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "callToAction";
      }
    | {
        introContent?: {}[];
        cardStyle: "fullBG" | "insetImage" | "noImage";
        cards?: {
          richText?: {}[];
          link?: {
            type?: "reference" | "custom";
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          media?: string | Media;
          useOverlay?: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "cardGrid";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        cardStyle: "fullBG" | "insetImage" | "noImage";
        slides?: {
          richText?: {}[];
          link?: {
            type?: "reference" | "custom";
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          media: string | Media;
          useOverlay?: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "cardSlider";
      }
    | {
        introContent?: {}[];
        media1?: string | Media;
        media2?: string | Media;
        media3?: string | Media;
        id?: string;
        blockName?: string;
        blockType: "careerSearch";
      }
    | {
        enableGrayBackground?: boolean;
        columns?: {
          width: "oneThird" | "half" | "twoThirds" | "full";
          alignment: "left" | "center" | "right";
          richText?: {}[];
          links?: {
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "content";
      }
    | {
        cellWidth?: "two" | "three";
        invertColors?: boolean;
        enableCellNumbers?: boolean;
        introContent?: {}[];
        cells?: {
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "contentGrid";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        slides?: {
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "contentSlider";
      }
    | {
        introContent?: {}[];
        id?: string;
        blockName?: string;
        blockType: "housingMap";
      }
    | {
        introContent?: {}[];
        id?: string;
        blockName?: string;
        blockType: "housingList";
      }
    | {
        richText?: {}[];
        form: string | Form;
        id?: string;
        blockName?: string;
        blockType: "embeddedForm";
      }
    | {
        introContent?: {}[];
        locations?: (string | Location)[];
        id?: string;
        blockName?: string;
        blockType: "locations";
      }
    | {
        media: string | Media;
        useVimeo?: boolean;
        vimeoID: string;
        aspectRatio?: "56.25" | "75";
        size?: "normal" | "wide" | "fullscreen";
        caption?: {}[];
        id?: string;
        blockName?: string;
        blockType: "media";
      }
    | {
        collage?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaCollage";
      }
    | {
        alignment: "contentOnLeft" | "contentOnRight";
        overlap?: boolean;
        invertColors?: boolean;
        richText: {}[];
        media: string | Media;
        embeddedVideo?: {
          embed?: boolean;
          poster?: string | Media;
          platform?: "youtube" | "vimeo";
          videoID: string;
          aspectRatio?: "56.25" | "75";
        };
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaContent";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        slides?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaSlider";
      }
    | {
        items?: {
          label: string;
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "stickyList";
      }
    | {
        id?: string;
        blockName?: string;
        blockType: "divider";
      }
  )[];
  fullTitle?: string;
  excerpt?: string;
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
    image?: string | Media;
  };
  status?: "published" | "draft";
  slug?: string;
  parent?: string | Page;
  subsite?: string | Subsite;
  color?: "green" | "blue" | "red" | "purple";
  author?: string | User;
  preview?: string;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  title: string;
  hero?: {
    type:
      | "basic"
      | "content"
      | "contentMedia"
      | "contentMedia2"
      | "contentSidebar"
      | "columnsBelow"
      | "quickNav"
      | "fullscreenBackground"
      | "fullscreenSlider";
    basic?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    content?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    contentMedia?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      media: string | Media;
    };
    contentMedia2?: {
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      media: string | Media;
    };
    contentSidebar?: {
      mainContent?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      sidebarContent?: {}[];
    };
    columnsBelow?: {
      backgroundMedia: string | Media;
      useOverlay?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      columns?: {
        heading: string;
        description: string;
        link?: {
          type?: "reference" | "custom";
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    fullscreenBackground?: {
      invertColors?: boolean;
      backgroundMedia: string | Media;
      useOverlay?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    quickNav?: {
      invertColors?: boolean;
      backgroundMedia: string | Media;
      useOverlay?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      columns?: {
        heading: string;
        description: string;
        link?: {
          type?: "reference" | "custom";
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
    };
    fullscreenSlider?: {
      useStaticContent?: boolean;
      richText?: {}[];
      links?: {
        link?: {
          appearance?: "text" | "primaryButton" | "secondaryButton";
          type?: "reference" | "custom";
          label: string;
          reference:
            | {
                value: string | Page;
                relationTo: "pages";
              }
            | {
                value: string | Post;
                relationTo: "posts";
              }
            | {
                value: string | Housing;
                relationTo: "housing";
              };
          url: string;
        };
        id?: string;
      }[];
      slides?: {
        backgroundMedia: string | Media;
        useOverlay?: boolean;
        richText?: {}[];
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
      }[];
    };
  };
  layout?: (
    | {
        appearance?: "default" | "condensed";
        sections?: {
          label: string;
          openOnInit?: boolean;
          columns?: {
            width: "oneThird" | "half" | "twoThirds" | "full";
            alignment: "left" | "center" | "right";
            richText?: {}[];
            links?: {
              link?: {
                type?: "reference" | "custom";
                label: string;
                reference:
                  | {
                      value: string | Page;
                      relationTo: "pages";
                    }
                  | {
                      value: string | Post;
                      relationTo: "posts";
                    }
                  | {
                      value: string | Housing;
                      relationTo: "housing";
                    };
                url: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "accordion";
      }
    | {
        introContent?: {}[];
        id?: string;
        blockName?: string;
        blockType: "blackbaudForm";
      }
    | {
        invertColors?: boolean;
        backgroundMedia?: string | Media;
        useOverlay?: boolean;
        richText?: {}[];
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "callToAction";
      }
    | {
        introContent?: {}[];
        cardStyle: "fullBG" | "insetImage" | "noImage";
        cards?: {
          richText?: {}[];
          link?: {
            type?: "reference" | "custom";
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          media?: string | Media;
          useOverlay?: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "cardGrid";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        cardStyle: "fullBG" | "insetImage" | "noImage";
        slides?: {
          richText?: {}[];
          link?: {
            type?: "reference" | "custom";
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          media: string | Media;
          useOverlay?: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "cardSlider";
      }
    | {
        introContent?: {}[];
        media1?: string | Media;
        media2?: string | Media;
        media3?: string | Media;
        id?: string;
        blockName?: string;
        blockType: "careerSearch";
      }
    | {
        enableGrayBackground?: boolean;
        columns?: {
          width: "oneThird" | "half" | "twoThirds" | "full";
          alignment: "left" | "center" | "right";
          richText?: {}[];
          links?: {
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "content";
      }
    | {
        cellWidth?: "two" | "three";
        invertColors?: boolean;
        enableCellNumbers?: boolean;
        introContent?: {}[];
        cells?: {
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "contentGrid";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        slides?: {
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "contentSlider";
      }
    | {
        richText?: {}[];
        form: string | Form;
        id?: string;
        blockName?: string;
        blockType: "embeddedForm";
      }
    | {
        introContent?: {}[];
        id?: string;
        blockName?: string;
        blockType: "housingMap";
      }
    | {
        introContent?: {}[];
        id?: string;
        blockName?: string;
        blockType: "housingList";
      }
    | {
        introContent?: {}[];
        locations?: (string | Location)[];
        id?: string;
        blockName?: string;
        blockType: "locations";
      }
    | {
        media: string | Media;
        useVimeo?: boolean;
        vimeoID: string;
        aspectRatio?: "56.25" | "75";
        size?: "normal" | "wide" | "fullscreen";
        caption?: {}[];
        id?: string;
        blockName?: string;
        blockType: "media";
      }
    | {
        collage?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaCollage";
      }
    | {
        alignment: "contentOnLeft" | "contentOnRight";
        overlap?: boolean;
        invertColors?: boolean;
        richText: {}[];
        media: string | Media;
        embeddedVideo?: {
          embed?: boolean;
          poster?: string | Media;
          platform?: "youtube" | "vimeo";
          videoID: string;
          aspectRatio?: "56.25" | "75";
        };
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaContent";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        slides?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaSlider";
      }
    | {
        items?: {
          label: string;
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "stickyList";
      }
    | {
        id?: string;
        blockName?: string;
        blockType: "divider";
      }
  )[];
  slug?: string;
  category: string | PostCategory;
  subsite?: string | Subsite;
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
    image?: string | Media;
  };
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "housing".
 */
export interface Housing {
  title: string;
  address?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?:
      | "None"
      | "Alabama"
      | "Alaska"
      | "Arizona"
      | "Arkansas"
      | "California"
      | "Colorado"
      | "Connecticut"
      | "Delaware"
      | "Florida"
      | "Georgia"
      | "Hawaii"
      | "Idaho"
      | "Illinois"
      | "Indiana"
      | "Iowa"
      | "Kansas"
      | "Kentucky"
      | "Louisiana"
      | "Maine"
      | "Maryland"
      | "Massachusetts"
      | "Michigan"
      | "Minnesota"
      | "Mississippi"
      | "Missouri"
      | "Montana"
      | "Nebraska"
      | "Nevada"
      | "New Hampshire"
      | "New Jersey"
      | "New Mexico"
      | "New York"
      | "North Carolina"
      | "North Dakota"
      | "Ohio"
      | "Oklahoma"
      | "Oregon"
      | "Pennsylvania"
      | "Rhode Island"
      | "South Carolina"
      | "South Dakota"
      | "Tennessee"
      | "Texas"
      | "Utah"
      | "Vermont"
      | "Virginia"
      | "Washington"
      | "West Virginia"
      | "Wisconsin"
      | "Wyoming";
    zip?: string;
    coords?: {
      lat?: number;
      lng?: number;
    };
  };
  contacts?: {
    type?: "mailto" | "tel" | "fax";
    label?: string;
    value?: string;
    id?: string;
  }[];
  layout?: (
    | {
        appearance?: "default" | "condensed";
        sections?: {
          label: string;
          openOnInit?: boolean;
          columns?: {
            width: "oneThird" | "half" | "twoThirds" | "full";
            alignment: "left" | "center" | "right";
            richText?: {}[];
            links?: {
              link?: {
                type?: "reference" | "custom";
                label: string;
                reference:
                  | {
                      value: string | Page;
                      relationTo: "pages";
                    }
                  | {
                      value: string | Post;
                      relationTo: "posts";
                    }
                  | {
                      value: string | Housing;
                      relationTo: "housing";
                    };
                url: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "accordion";
      }
    | {
        invertColors?: boolean;
        backgroundMedia?: string | Media;
        useOverlay?: boolean;
        richText?: {}[];
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "callToAction";
      }
    | {
        introContent?: {}[];
        cardStyle: "fullBG" | "insetImage" | "noImage";
        cards?: {
          richText?: {}[];
          link?: {
            type?: "reference" | "custom";
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          media?: string | Media;
          useOverlay?: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "cardGrid";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        cardStyle: "fullBG" | "insetImage" | "noImage";
        slides?: {
          richText?: {}[];
          link?: {
            type?: "reference" | "custom";
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          media: string | Media;
          useOverlay?: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "cardSlider";
      }
    | {
        introContent?: {}[];
        media1?: string | Media;
        media2?: string | Media;
        media3?: string | Media;
        id?: string;
        blockName?: string;
        blockType: "careerSearch";
      }
    | {
        enableGrayBackground?: boolean;
        columns?: {
          width: "oneThird" | "half" | "twoThirds" | "full";
          alignment: "left" | "center" | "right";
          richText?: {}[];
          links?: {
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
          }[];
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "content";
      }
    | {
        cellWidth?: "two" | "three";
        invertColors?: boolean;
        enableCellNumbers?: boolean;
        introContent?: {}[];
        cells?: {
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "contentGrid";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        slides?: {
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "contentSlider";
      }
    | {
        richText?: {}[];
        form: string | Form;
        id?: string;
        blockName?: string;
        blockType: "embeddedForm";
      }
    | {
        introContent?: {}[];
        locations?: (string | Location)[];
        id?: string;
        blockName?: string;
        blockType: "locations";
      }
    | {
        media: string | Media;
        useVimeo?: boolean;
        vimeoID: string;
        aspectRatio?: "56.25" | "75";
        size?: "normal" | "wide" | "fullscreen";
        caption?: {}[];
        id?: string;
        blockName?: string;
        blockType: "media";
      }
    | {
        collage?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaCollage";
      }
    | {
        alignment: "contentOnLeft" | "contentOnRight";
        overlap?: boolean;
        invertColors?: boolean;
        richText: {}[];
        media: string | Media;
        embeddedVideo?: {
          embed?: boolean;
          poster?: string | Media;
          platform?: "youtube" | "vimeo";
          videoID: string;
          aspectRatio?: "56.25" | "75";
        };
        links?: {
          link?: {
            appearance?: "text" | "primaryButton" | "secondaryButton";
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaContent";
      }
    | {
        introContent?: {}[];
        backgroundType?: "light" | "color";
        slides?: {
          media: string | Media;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "mediaSlider";
      }
    | {
        items?: {
          label: string;
          richText?: {}[];
          enableLink?: boolean;
          link?: {
            type?: "reference" | "custom";
            label: string;
            reference:
              | {
                  value: string | Page;
                  relationTo: "pages";
                }
              | {
                  value: string | Post;
                  relationTo: "posts";
                }
              | {
                  value: string | Housing;
                  relationTo: "housing";
                };
            url: string;
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: "stickyList";
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
    image?: string | Media;
  };
  slug?: string;
  categories?: (string | HousingCategory)[];
  subsite?: string | Subsite;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    card?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    portrait?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    square?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    feature?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    meta?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    hero?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
  alt: string;
  fallback?: string | Media;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  title: string;
  emailTo?: string;
  successMessage?: {}[];
  redirect?: string;
  submitButtonLabel?: string;
  fields?: (
    | {
        name: string;
        label: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: "text";
      }
    | {
        name: string;
        label: string;
        width?: number;
        defaultValue?: string;
        options?: {
          label: string;
          value: string;
          id?: string;
        }[];
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: "select";
      }
    | {
        name: string;
        label: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: "email";
      }
    | {
        name: string;
        label: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: "state";
      }
    | {
        name: string;
        label: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: "country";
      }
    | {
        name: string;
        label: string;
        width?: number;
        required?: boolean;
        defaultValue?: boolean;
        id?: string;
        blockName?: string;
        blockType: "checkbox";
      }
    | {
        message?: {}[];
        id?: string;
        blockName?: string;
        blockType: "message";
      }
  )[];
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  name: string;
  address?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?:
      | "None"
      | "Alabama"
      | "Alaska"
      | "Arizona"
      | "Arkansas"
      | "California"
      | "Colorado"
      | "Connecticut"
      | "Delaware"
      | "Florida"
      | "Georgia"
      | "Hawaii"
      | "Idaho"
      | "Illinois"
      | "Indiana"
      | "Iowa"
      | "Kansas"
      | "Kentucky"
      | "Louisiana"
      | "Maine"
      | "Maryland"
      | "Massachusetts"
      | "Michigan"
      | "Minnesota"
      | "Mississippi"
      | "Missouri"
      | "Montana"
      | "Nebraska"
      | "Nevada"
      | "New Hampshire"
      | "New Jersey"
      | "New Mexico"
      | "New York"
      | "North Carolina"
      | "North Dakota"
      | "Ohio"
      | "Oklahoma"
      | "Oregon"
      | "Pennsylvania"
      | "Rhode Island"
      | "South Carolina"
      | "South Dakota"
      | "Tennessee"
      | "Texas"
      | "Utah"
      | "Vermont"
      | "Virginia"
      | "Washington"
      | "West Virginia"
      | "Wisconsin"
      | "Wyoming";
    zip?: string;
    coords?: {
      lat?: number;
      lng?: number;
    };
  };
  contacts?: {
    type?: "mailto" | "tel" | "fax";
    label?: string;
    value?: string;
    id?: string;
  }[];
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
    image?: string | Media;
  };
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "housing-categories".
 */
export interface HousingCategory {
  title: string;
  slug?: string;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "subsites".
 */
export interface Subsite {
  title: string;
  menuItems?: {
    type?: "link" | "subMenu";
    link?: {
      type?: "reference" | "custom";
      label: string;
      reference:
        | {
            value: string | Page;
            relationTo: "pages";
          }
        | {
            value: string | Post;
            relationTo: "posts";
          }
        | {
            value: string | Housing;
            relationTo: "housing";
          };
      url: string;
    };
    label: string;
    subMenu?: {
      column1?: (
        | {
            appearance?: "primary" | "secondary" | "arrow";
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuLink";
          }
        | {
            content: string;
            id?: string;
            blockName?: string;
            blockType: "menuDescription";
          }
        | {
            media: string | Media;
            headline: string;
            link?: {
              type?: "reference" | "custom";
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuFeature";
          }
      )[];
      enableColumn2?: boolean;
      column2?: (
        | {
            appearance?: "primary" | "secondary" | "arrow";
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuLink";
          }
        | {
            content: string;
            id?: string;
            blockName?: string;
            blockType: "menuDescription";
          }
        | {
            media: string | Media;
            headline: string;
            link?: {
              type?: "reference" | "custom";
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuFeature";
          }
      )[];
      enableColumn3?: boolean;
      column3?: (
        | {
            appearance?: "primary" | "secondary" | "arrow";
            link?: {
              type?: "reference" | "custom";
              label: string;
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuLink";
          }
        | {
            content: string;
            id?: string;
            blockName?: string;
            blockType: "menuDescription";
          }
        | {
            media: string | Media;
            headline: string;
            link?: {
              type?: "reference" | "custom";
              reference:
                | {
                    value: string | Page;
                    relationTo: "pages";
                  }
                | {
                    value: string | Post;
                    relationTo: "posts";
                  }
                | {
                    value: string | Housing;
                    relationTo: "housing";
                  };
              url: string;
            };
            id?: string;
            blockName?: string;
            blockType: "menuFeature";
          }
      )[];
    };
    id?: string;
  }[];
  slug?: string;
  color?: "green" | "blue" | "red" | "purple";
  home: string | Page;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  title: string;
  color?: "green" | "blue" | "red" | "purple";
  slug?: string;
  subsite?: string | Subsite;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  column1?: {
    appearance?: "primary" | "secondary" | "tertiary";
    label?: string;
    useLink?: boolean;
    link?: {
      type?: "reference" | "custom";
      reference:
        | {
            value: string | Page;
            relationTo: "pages";
          }
        | {
            value: string | Post;
            relationTo: "posts";
          }
        | {
            value: string | Housing;
            relationTo: "housing";
          };
      url: string;
    };
    id?: string;
  }[];
  column2?: {
    appearance?: "secondary" | "tertiary";
    label?: string;
    useLink?: boolean;
    link?: {
      type?: "reference" | "custom";
      reference:
        | {
            value: string | Page;
            relationTo: "pages";
          }
        | {
            value: string | Post;
            relationTo: "posts";
          }
        | {
            value: string | Housing;
            relationTo: "housing";
          };
      url: string;
    };
    id?: string;
  }[];
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "meta".
 */
export interface Meta {
  socialMediaLinks?: {
    type: "facebook" | "vimeo" | "twitter" | "linkedin" | "instagram";
    url: string;
    id?: string;
  }[];
  legalLinks?: {
    link?: {
      type?: "reference" | "custom";
      label: string;
      reference:
        | {
            value: string | Page;
            relationTo: "pages";
          }
        | {
            value: string | Post;
            relationTo: "posts";
          }
        | {
            value: string | Housing;
            relationTo: "housing";
          };
      url: string;
    };
    id?: string;
  }[];
  locations?: (string | Location)[];
  phone?: string;
  nationalPhone?: string;
  fax?: string;
  popularSearchTerms?: {
    term: string;
    id?: string;
  }[];
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  placement: "global" | "subsite";
  subsites: (string | Subsite)[];
  backgroundColor?: "matchTheme" | "green" | "blue" | "red" | "purple";
  content: {}[];
  links?: {
    link?: {
      appearance?: "text" | "primaryButton" | "secondaryButton";
      type?: "reference" | "custom";
      label: string;
      reference:
        | {
            value: string | Page;
            relationTo: "pages";
          }
        | {
            value: string | Post;
            relationTo: "posts";
          }
        | {
            value: string | Housing;
            relationTo: "housing";
          };
      url: string;
    };
    id?: string;
  }[];
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "search".
 */
export interface SearchResult {
  title: string;
  description?: string;
  keywords?: string;
  slug: string;
  media?: string | Media;
  doc:
    | {
        value: string | Page;
        relationTo: "pages";
      }
    | {
        value: string | Post;
        relationTo: "posts";
      }
    | {
        value: string | Housing;
        relationTo: "housing";
      }
    | {
        value: string | Person;
        relationTo: "people";
      }
    | {
        value: string | Location;
        relationTo: "locations";
      };
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  name: string;
  position?: string;
  contacts?: {
    type?: "mailto" | "tel" | "fax";
    label?: string;
    value?: string;
    id?: string;
  }[];
  socialMediaLinks?: {
    type: "facebook" | "vimeo" | "twitter" | "linkedin" | "instagram";
    url: string;
    id?: string;
  }[];
  richText?: {}[];
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
    image?: string | Media;
  };
  slug?: string;
  home?: string | Page;
}
/**
 * This interface was referenced by `RealWorld`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  form: string | Form;
  submissionData?: {
    field: string;
    value: string;
    id?: string;
  }[];
}
