/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Butler_API_Entities_UserPrivate model
 */
export interface Ref {
  id?: string;
  login?: string;
  name?: string;
  email?: string;
  avatar_url?: string;
  given_name?: string;
  family_name?: string;
  picture?: string;
  locale?: string;
  supporter?: string;
  created_at?: string;
  updated_at?: string;
  access_token?: string;
  role?: string;
  projects?: Project;
  [k: string]: unknown;
}
/**
 * Butler_API_Entities_Project model
 */
export interface Project {
  slug?: string;
  owner?: string;
  parent_project?: Project;
  /**
   * Project Name
   */
  name?: string;
  /**
   * Project Description
   */
  description?: string;
  /**
   * Repository
   */
  repository_id?: string;
  /**
   * Code Repository ID
   */
  code_repository_id?: string;
  created_at?: string;
  updated_at?: string;
  [k: string]: unknown;
}
