/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Referencing {
  a: ExampleSchema
  [k: string]: unknown
}
export interface ExampleSchema {
  /**
   * @maxItems 5
   */
  b?:
    | []
    | [number]
    | [number, number]
    | [number, number, number]
    | [number, number, number, number]
    | [number, number, number, number, number]
  [k: string]: unknown
}
