/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SafeTypeNames {
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "stra'nge#name".
 */
export interface StraNgeName {
  a: string
  b?: number
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "keepUPPERCASE".
 */
export interface KeepUPPERCASE {
  a?: 'a' | 'b' | 'c'
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "snake_case".
 */
export interface SnakeCase {
  a?: boolean
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "_startsWithUnderscore".
 */
export interface _StartsWithUnderscore {
  a?: boolean
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "_StartsWithUnderscoreUppercase".
 */
export interface _StartsWithUnderscoreUppercase {
  a?: boolean
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "EndsWithUnderscore_".
 */
export interface EndsWithUnderscore_ {
  a?: boolean
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "UPPER_CASE".
 */
export interface UPPER_CASE {
  a?: boolean
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "______________".
 */
export interface ______________ {
  a?: boolean
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "camelCase".
 */
export interface CamelCase {
  a?: {
    [k: string]: unknown
  }
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "kebab-case".
 */
export interface KebabCase {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` " startsWithSpace".
 */
export interface StartsWithSpace {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "contains space".
 */
export interface ContainsSpace {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "5tartsWithDigit".
 */
export interface TartsWithDigit {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` " 5tartsWithBlankAndDigit".
 */
export interface TartsWithBlankAndDigit {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "endsWithDigi7".
 */
export interface EndsWithDigi7 {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "contains4digit".
 */
export interface Contains4Digit {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` ".startsWithPeriod".
 */
export interface StartsWithPeriod {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "endsWithPeriod.".
 */
export interface EndsWithPeriod {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "contains...period".
 */
export interface ContainsPeriod {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` ",startsWithComma".
 */
export interface StartsWithComma {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "endsWithComma,".
 */
export interface EndsWithComma {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "contains,,Comma".
 */
export interface ContainsComma {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "$startsWithDollar".
 */
export interface $StartsWithDollar {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "endsWithDollar$".
 */
export interface EndsWithDollar$ {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "contains$Dollar".
 */
export interface Contains$Dollar {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "$".
 */
export interface $ {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "UPPERCASE".
 */
export interface UPPERCASE {
  a?: string
  [k: string]: unknown
}
/**
 * This interface was referenced by `SafeTypeNames`'s JSON-Schema
 * via the `definition` "Startsuppercase".
 */
export interface Startsuppercase {
  a?: string
  [k: string]: unknown
}
