/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaWithSubschema {
  firstName: string;
  friend?: {
    knowsFrom: "work" | "school" | "other";
  };
  coworker?: {
    company?: {
      name: string;
    };
    [k: string]: KString;
  };
}

export const enum KString {
  red = 10,
  green = 20,
  blue = 30
}
