/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UnionWithProps = (
  | {
      obj_type: "Foo";
      foo_type?: string;
    }
  | {
      obj_type: "Bar";
      bar_type?: string;
      team: string;
      health: number;
    }
) & {
  coords: number;
  id: number;
};
